"""add_directive_module

Revision ID: 018faa644e87
Revises: a62eedeeec8b
Create Date: 2026-05-16 16:47:27.539563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '018faa644e87'
down_revision: Union[str, None] = 'a62eedeeec8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('issuer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issuer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directives_id'), 'directives', ['id'], unique=False)
    op.create_index(op.f('ix_directives_issuer_id'), 'directives', ['issuer_id'], unique=False)
    op.create_index(op.f('ix_directives_status'), 'directives', ['status'], unique=False)
    op.create_index(op.f('ix_directives_title'), 'directives', ['title'], unique=False)
    op.create_table('directive_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('directive_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_mime', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['directive_id'], ['directives.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directive_attachments_directive_id'), 'directive_attachments', ['directive_id'], unique=False)
    op.create_table('directive_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('directive_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['directive_id'], ['directives.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directive_comments_directive_id'), 'directive_comments', ['directive_id'], unique=False)
    op.create_table('directive_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('directive_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('old_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=True),
    sa.Column('old_progress', sa.Integer(), nullable=True),
    sa.Column('new_progress', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['directive_id'], ['directives.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directive_history_directive_id'), 'directive_history', ['directive_id'], unique=False)
    op.create_table('directive_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('directive_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['directive_id'], ['directives.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directive_tasks_directive_id'), 'directive_tasks', ['directive_id'], unique=False)
    op.create_table('directive_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('directive_id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['directive_id'], ['directives.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directive_units_directive_id'), 'directive_units', ['directive_id'], unique=False)
    op.add_column('notifications', sa.Column('link_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'link_url')
    op.drop_index(op.f('ix_directive_units_directive_id'), table_name='directive_units')
    op.drop_table('directive_units')
    op.drop_index(op.f('ix_directive_tasks_directive_id'), table_name='directive_tasks')
    op.drop_table('directive_tasks')
    op.drop_index(op.f('ix_directive_history_directive_id'), table_name='directive_history')
    op.drop_table('directive_history')
    op.drop_index(op.f('ix_directive_comments_directive_id'), table_name='directive_comments')
    op.drop_table('directive_comments')
    op.drop_index(op.f('ix_directive_attachments_directive_id'), table_name='directive_attachments')
    op.drop_table('directive_attachments')
    op.drop_index(op.f('ix_directives_title'), table_name='directives')
    op.drop_index(op.f('ix_directives_status'), table_name='directives')
    op.drop_index(op.f('ix_directives_issuer_id'), table_name='directives')
    op.drop_index(op.f('ix_directives_id'), table_name='directives')
    op.drop_table('directives')
    # ### end Alembic commands ###
