"""add_departments_staff_relations

Revision ID: 09e354bd1c8e
Revises: 33d02ac87f54
Create Date: 2026-05-16 20:51:07.520822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '09e354bd1c8e'
down_revision: Union[str, None] = '33d02ac87f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('dept_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('employee_code', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('position', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_staff_department_id'), 'staff', ['department_id'], unique=False)
    op.create_index(op.f('ix_staff_employee_code'), 'staff', ['employee_code'], unique=True)
    op.create_index(op.f('ix_staff_full_name'), 'staff', ['full_name'], unique=False)
    op.create_index(op.f('ix_staff_id'), 'staff', ['id'], unique=False)
    op.create_table('task_cooperating_departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_cooperating_departments_task_id'), 'task_cooperating_departments', ['task_id'], unique=False)
    op.add_column('directive_units', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'directive_units', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.add_column('directives', sa.Column('responsible_department_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_directives_responsible_department_id'), 'directives', ['responsible_department_id'], unique=False)
    op.create_foreign_key(None, 'directives', 'departments', ['responsible_department_id'], ['id'], ondelete='SET NULL')
    op.add_column('documents', sa.Column('source_document_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('source_directive_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('responsible_department_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_documents_responsible_department_id'), 'documents', ['responsible_department_id'], unique=False)
    op.create_index(op.f('ix_documents_source_directive_id'), 'documents', ['source_directive_id'], unique=False)
    op.create_index(op.f('ix_documents_source_document_id'), 'documents', ['source_document_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'directives', ['source_directive_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'documents', 'documents', ['source_document_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'documents', 'departments', ['responsible_department_id'], ['id'], ondelete='SET NULL')
    op.add_column('tasks', sa.Column('source_document_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('source_directive_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('responsible_department_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tasks_responsible_department_id'), 'tasks', ['responsible_department_id'], unique=False)
    op.create_index(op.f('ix_tasks_source_directive_id'), 'tasks', ['source_directive_id'], unique=False)
    op.create_index(op.f('ix_tasks_source_document_id'), 'tasks', ['source_document_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'departments', ['responsible_department_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tasks', 'directives', ['source_directive_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tasks', 'documents', ['source_document_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_source_document_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_source_directive_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_responsible_department_id'), table_name='tasks')
    op.drop_column('tasks', 'responsible_department_id')
    op.drop_column('tasks', 'source_directive_id')
    op.drop_column('tasks', 'source_document_id')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_source_document_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_source_directive_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_responsible_department_id'), table_name='documents')
    op.drop_column('documents', 'responsible_department_id')
    op.drop_column('documents', 'source_directive_id')
    op.drop_column('documents', 'source_document_id')
    op.drop_constraint(None, 'directives', type_='foreignkey')
    op.drop_index(op.f('ix_directives_responsible_department_id'), table_name='directives')
    op.drop_column('directives', 'responsible_department_id')
    op.drop_constraint(None, 'directive_units', type_='foreignkey')
    op.drop_column('directive_units', 'department_id')
    op.drop_index(op.f('ix_task_cooperating_departments_task_id'), table_name='task_cooperating_departments')
    op.drop_table('task_cooperating_departments')
    op.drop_index(op.f('ix_staff_id'), table_name='staff')
    op.drop_index(op.f('ix_staff_full_name'), table_name='staff')
    op.drop_index(op.f('ix_staff_employee_code'), table_name='staff')
    op.drop_index(op.f('ix_staff_department_id'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
